# Warning, do not check out untrusted code with
# the pull_request_target event.
on:
  pull_request_target:
    types: [ opened, edited ]
name: conventional-release-labels
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/conventional-release-labels@v1.3.0
        with:
          type_labels: '{ "breaking": ":rotating_light: BREAKING CHANGE", "feat": "feature", "fix": "fix", "docs": "docs", "chore": "chore", "enhancement": "enhancement", "breaking": "breaking-change" }'
